# Change these first
owner: ZianTT # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Blog
    url: https://ziantt.top

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  cname: status.ziantt.top
  # baseUrl: /your-repo-name
  logoUrl: https://npm.elemecdn.com/ziantt-blog-assets/img/avatar.jpg
  name: ZianTT Status
  introTitle: "Project Status of ZianTT<br>ZianTT的Status"
  introMessage: This is a status page which displays some project statuses maintained by ZianTT<br>这是个由ZianTT维护的项目们的状态页喵
  publish: true
  apiBaseUrl: https://gh-api.bitf1a5h.eu.org
  userContentBaseUrl: https://gh-usercontent.bitf1a5h.eu.org
  navbar:
    - title: Status
      href: /
    - title: Blog
      href: https://ziantt.top
  
i18n:
  footer: This page is powered by [ZianTT](https://ziantt.top)<br>本页面由[ZianTT](https://ziantt.top)强力驱动喵
  url: "URL"
  status: "Status"
  history: "历史记录"
  responseTime: "响应时间"
  uptime: "Uptime"
  up: "🟩 在线"
  degraded: "🟨 有些不可以哦"
  down: "🟥 寄了"
  responseTimeGraphAlt: "响应时间趋势"
  Time: "响应时间"
  responseTimeDay: "24-hour response time"
  responseTimeWeek: "7-day response time"
  responseTimeMonth: "30-day response time"
  responseTimeYear: "1-year response time"
  uptimeDay: "24-hour uptime"
  uptimeWeek: "7-day uptime"
  uptimeMonth: "30-day uptime"
  uptimeYear: "1-year uptime"
  liveStatus: "当前Status"
  liveStatusHtmlComment: "<!--live status-->"
  allSystemsOperational: "🟩 都在哦"
  degradedPerformance: "🟨 可能会不太稳喵"
  completeOutage: "🟥 都寄了"
  partialOutage: "🟧 有些不可以哦"
  activeIncidents: 处理中的事件
  incidentReport: "事件 #$NUMBER 的报告 →"
  activeIncidentSummary: Opened at $DATE with $POSTS posts
  incidentTitle: Incident $NUMBER Details
  incidentDetails: 事件详情
  incidentFixed: 已修复
  incidentOngoing: Ongoing
  incidentOpenedAt: Opened at
  incidentClosedAt: Closed at
  incidentSubscribe: 订阅更新
  incidentViewOnGitHub: 在 GitHub 上 查看
  incidentCommentSummary: Posted at $DATE by $AUTHOR
  incidentBack: ← 返回到所有事件
  pastIncidents: 过去事件
  pastIncidentsResolved: Resolved in $MINUTES minutes with $POSTS posts
  overallUptime: "总Uptime: $UPTIME"
  overallUptimeTitle: 总Uptime
  averageResponseTime: "平均响应时间: $TIMEms"
  averageResponseTimeTitle: 平均响应时间
  sevelDayResponseTime: 7天内 响应时间
  responseTimeMs: 响应时间 (ms)
  ms: ms
  loading: 爬爬爬...
  navGitHub: GitHub
  rateLimitExceededTitle: Rate limit exceedeed
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: 出现错误
  errorIntro: 当获取最新Status信息时，出错了喵
  errorText: 过一会再刷新喵
  errorHome: 回到窝里

skipDescriptionUpdate: true

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
