# Change these first
owner: ZianTT # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Blog
    url: https://ziantt.top

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  cname: status.ziantt.top
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ZianTT Status
  introTitle: "Project Status maintained by ZianTT"
  introMessage: This is a status page which displays some project statuses maintained by ZianTT
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
